AUTH_SERVER = "http://localhost:5000"
BASTION_SERVER = "http://localhost:5001"
DATA_SERVER = "http://localhost:5002"
HEADER_NAME = "X-Cerebro-Token"
COOKIE = "charles"
AZURE = "https://login.microsoftonline.com"
